extra-deps: []
resolver: lts-13.21
flags: {}
packages:
- '.'
- extra-dep: true
  location: {commit: 874e53221cf9eea2f96c0a6b907325ce05ee633c, git: 'https://github.com/luna/luna.git'}
  subdirs:
    - lib/container
    - lib/prologue
    - lib/typelevel
    - lib/convert
    - lib/exception
    - lib/layered-state
    - lib/functor-utils
    - lib/impossible
    - lib/lens-utils
    - lib/monoid
    - lib/monad-branch
    - lib/th-builder
- extra-dep: true
  location: {commit: e322bdd961262fd2811320774d17b14fe07b297a, git: 'https://github.com/mwu-tow/pecoff'}